### ISSUE TITLE
关于token过期问题

### ISSUE THREAD

**Issue by tree-eighteen** [fuzhengwei/chatglm-sdk-java#2]
spring boot 2.7 ，现在的情况是，当使用超过30分钟后，就会出现 token 过期，过期后一直无法使用，除非重启项目。

我看了代码，没找到有调用获取 token 的地方，是哪儿没处理好么。

<img width="683" alt="image" src="https://github.com/fuzhengwei/chatglm-sdk-java/assets/41732381/940d8767-0b63-4b8a-9b02-08d9b5c10073">

**Comment by tree-eighteen** [comment]
是不是这个问题？

![image](https://github.com/fuzhengwei/chatglm-sdk-java/assets/41732381/57257bc6-737c-49d4-b987-ba2edb0b2905)

**Comment by fuzhengwei** [comment]
处理好了
